# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: goreleasertest

env:
  - PROJECT_ROOT={{ .Env.PWD }}

before:
  hooks:
    - go mod tidy

builds:
  # Linux builds with static musl-libc via Zig
  - id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
      - CC={{ .Env.PROJECT_ROOT }}/scripts/zig-cc.sh
      - CXX={{ .Env.PROJECT_ROOT }}/scripts/zig-cxx.sh
    ldflags:
      - -s -w
    tags:
      # Avoid glibc/NSS at runtime for fully static binaries
      - netgo
      - osusergo

  # Windows builds via Zig (MinGW-w64 headers)
  - id: windows
    goos: [windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
      - CC={{ .Env.PROJECT_ROOT }}/scripts/zig-cc.sh
      - CXX={{ .Env.PROJECT_ROOT }}/scripts/zig-cxx.sh
    ldflags:
      - -s -w

  # macOS builds via Zig
  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
      - CC={{ .Env.PROJECT_ROOT }}/scripts/zig-cc.sh
      - CXX={{ .Env.PROJECT_ROOT }}/scripts/zig-cxx.sh
    ldflags:
      - -s -w
    tags:
      # Avoid glibc/NSS at runtime for fully static binaries
      - netgo
      - osusergo

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
